name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-storybook-to-gh-pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.2.4
        with:
          install_command: yarn install
          build_command: yarn build-storybook
          path: storybook-static