name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-storybook-to-gh-pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Deploy storybook to GitHub Pages
        run: yarn deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
