name: Release

on:
  release:
    branches:
      - main
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: yarn install
        run: |
          yarn install
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" | sed 's/v//' >> $GITHUB_ENV
      - name: Configure GitHub
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Build new version
          run: yarn build
      - name: Publish new version
        run: yarn publish --new-version $RELEASE_VERSION --no-git-tag-version --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_CI_TOKEN }}
      - name: Push new package.json version
        run: |
          git commit -am "Bumped package.json to $RELEASE_VERSION"
          git push origin HEAD:main
